"""initial"""

from alembic import op
import sqlalchemy as sa

revision = "bd3cf0657410"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_auth_sessions_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "calendar_events",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "external_id"),
    )
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_calendar_events_end_time"), ["end_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_calendar_events_start_time"), ["start_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_calendar_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "chat_messages",
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("actions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_messages_user_id"), ["user_id"], unique=False)

    op.create_table(
        "google_connections",
        sa.Column("encrypted_tokens", sa.Text(), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("google_connections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_google_connections_user_id"), ["user_id"], unique=False)

    op.create_table(
        "oauth_states",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("oauth_states", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_states_user_id"), ["user_id"], unique=False)

    op.create_table(
        "proposals",
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_proposals_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("estimated_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_deadline"), ["deadline"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_activity",
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_activity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_activity_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_activity_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_activity_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_preferences",
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("preferred_start_time", sa.String(length=5), nullable=False),
        sa.Column("preferred_end_time", sa.String(length=5), nullable=False),
        sa.Column("preferred_days", sa.JSON(), nullable=False),
        sa.Column("default_reminder_minutes", sa.Integer(), nullable=False),
        sa.Column("preferred_task_length", sa.Integer(), nullable=False),
        sa.Column("break_preference", sa.Integer(), nullable=False),
        sa.Column("allow_weekend_scheduling", sa.Boolean(), nullable=False),
        sa.Column("personalization_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_preferences_user_id"), ["user_id"], unique=False)

    op.create_table(
        "scheduled_tasks",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scheduled_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scheduled_tasks_end_time"), ["end_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_scheduled_tasks_start_time"), ["start_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_scheduled_tasks_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scheduled_tasks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "reminders",
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("scheduled_task_id", sa.Integer(), nullable=True),
        sa.Column("reminder_time", sa.DateTime(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["scheduled_task_id"], ["scheduled_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reminders_reminder_time"), ["reminder_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_user_id"))
        batch_op.drop_index(batch_op.f("ix_reminders_status"))
        batch_op.drop_index(batch_op.f("ix_reminders_reminder_time"))

    op.drop_table("reminders")
    with op.batch_alter_table("scheduled_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduled_tasks_user_id"))
        batch_op.drop_index(batch_op.f("ix_scheduled_tasks_task_id"))
        batch_op.drop_index(batch_op.f("ix_scheduled_tasks_start_time"))
        batch_op.drop_index(batch_op.f("ix_scheduled_tasks_end_time"))

    op.drop_table("scheduled_tasks")
    with op.batch_alter_table("user_preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_preferences_user_id"))

    op.drop_table("user_preferences")
    with op.batch_alter_table("user_activity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_activity_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_activity_created_at"))
        batch_op.drop_index(batch_op.f("ix_user_activity_action"))

    op.drop_table("user_activity")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_user_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_tasks_deadline"))

    op.drop_table("tasks")
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposals_user_id"))

    op.drop_table("proposals")
    with op.batch_alter_table("oauth_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_states_user_id"))

    op.drop_table("oauth_states")
    with op.batch_alter_table("google_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_google_connections_user_id"))

    op.drop_table("google_connections")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_user_id"))

    op.drop_table("chat_messages")
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calendar_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_calendar_events_start_time"))
        batch_op.drop_index(batch_op.f("ix_calendar_events_end_time"))

    op.drop_table("calendar_events")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_sessions_token_hash"))
        batch_op.drop_index(batch_op.f("ix_auth_sessions_expires_at"))

    op.drop_table("auth_sessions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
